version: "3.9"

services:
  opensmtpd:
    build: ./image
    ports:
      - "8026:8025"           # expose SMTP locally
    volumes:
      - ./coverage_snapshots:/app/coverage   # coverage logs
    tty: true

  opensmtpd2:
    build: ./image
    ports:
      - "8027:8025"           # expose SMTP locally
    volumes:
      - ./coverage_snapshots:/app/coverage   # coverage logs
    tty: true